import React, { Component, PropTypes} from 'react';
import Header from '../Header';
import { browserHistory } from 'react-router';

export default class TermsOfUse extends Component{

  componentDidMount = ()=>{
    if(typeof window !== "undefined") {
      window.fbq('trackCustom', 'TermsOfUsePageView');
    }
  };
  goBackHandler = ()=>{
    browserHistory.goBack();
  }
  render(){
    return(
      <div className='static-pages'>
        <Header title='TERMS OF USE / USER AGREEMENT' onClick={this.goBackHandler} />
        <section className='static-content'>
          <div className='container'>
            <div className='row'>
              <p>This user agreement is an electronic record in terms of Information Technology Act, 2000 ("<b>Act</b>") and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008. This user agreement is generated by a computer system and does not require any physical or digital signatures. </p>
              <p>This user agreement is published for access and/or usage of “<b>Voot</b>” a premium digital video streaming service owned and operated by Viacom18 Media Private Limited ("<b>Service</b>").</p>
              <p>In these terms and conditions of use ("<b>Terms of Use</b>"), the following terms shall have the meaning as ascribed to them below:</p>
              <p>"<b>User</b>" refers to you, the person visiting, accessing and/or using the Service by means of any communication device.</p>
              <p>"<b>Viacom18</b>" refers to Viacom 18 Media Private Limited, a company incorporated under the Companies Act, 1956, having Corporate Identity No. U92100MH1995PTC095508 and having its registered office address at Zion Biz World, Subhash Road 'A', Vile Parle East, Mumbai 400057, India, which is the owner of all rights in this Service. </p>
              <p>All references to "<b>You</b>" and "<b>Your</b>" shall mean the User. All references to "<b>Viacom18</b>", "<b>Company</b>", "<b>We</b>", "<b>Us</b>" and "<b>Our</b>" shall mean Viacom18.
              </p>
              <p>This is a legal and binding agreement between You i.e. the User of the Service and the Company and states the terms that govern Your use of the Service. By accessing this Service, You consent, agree and undertake to abide, be bound by and adhere to the Terms of Use and if You do not agree to these terms of use, You should not access or use the Service and any use thereafter shall be unauthorized. </p>
              <p>By accessing and/or using the Service, You signify Your agreement to accept these binding Terms of Use herein. This document constitutes a legally binding user agreement between the Company and You. <u>IF YOU DO NOT AGREE WITH ANY OR ALL OF THE FOLLOWING TERMS OF USE (INCLUDING THE PRIVACY POLICY), PLEASE DO NOT ACCESS AND/OR USE THE SERVICE.</u></p>
              <p>Please review the Terms of Use from time-to-time. We reserve the right, at Our sole discretion, to change, modify or otherwise alter these Terms of Use at any time without prior notice. Such changes and/or modifications shall become effective immediately upon being posted/published on the Service herein. Your continued use of the Service following the posting of changes and/or modifications shall constitute Your acceptance of any revised Terms of Use. The Company retains the right at any time to deny or suspend access to all or part of the Service to anyone who the Company believes has violated any of these Terms of Use.</p>

              <h4>ACCESS TO THE SERVICE</h4>
              <ol>
                <li>
                  The Service is being provided to You for free and there are no subscription charges for the usage of the Service. However, the Company reserves the right to adopt any method of monetization through the Service in the future as it deems fit.
                </li>
                <li>
                  This Service is offered and made available only to Users above the age of 18 years (or above 21 years where a guardian is appointed as per the Majority Act of 1875) ("<b>Age of Majority</b>").
                </li>
                <li>
                  If You are under the Age of Majority and continue accessing the Service, the Company will assume that You have reviewed these Terms of Use and the Privacy Policy with Your parent/legal guardian and Your parent/legal guardian understands and agrees to it on Your behalf. If You are under the Age of Majority at the time of accessing and/or using the Service, Your access and usage of the Service shall be deemed to be subject to parental/legal guardian consent and under parental/legal guardian’s guidance at all times. You and Your parents/legal guardians confirm that the Service is offered to You for Your enjoyment and these Terms of Use shall constitute a legally binding user agreement between the Company and Your parents/guardians who are contracting on behalf of You. Where Users are below the Age of Majority, all references to "User", "You" and "Your" shall mean and include You and Your parents/ legal guardians acting for and on Your behalf for Your benefit.
                </li>
                <li>
                  Some content offered on the Service may not be suitable for some Users and therefore viewer discretion/parental discretion is advised. Also, some content offered on the Service may not be appropriate for viewership by persons below the Age of Majority. If You are under the Age of Majority, You may view the content only with prior consent of Your parents/legal guardians. Parents/legal guardians are advised to exercise discretion before allowing their children and/or wards to access this Service and/or any Material (as defined later). Parents and legal guardians are strictly advised to restrict the use of the Service by minors by opting for parental pin feature available within the Service (Kids Zone PIN). By opting for the Kids Zone PIN access will be restricted to kids section within the Service. Your access to and use of the Service is subject to these Terms of Use, Privacy Policy and all applicable laws, rules, and regulations in India.
                </li>
                <li>
                  The Company grants You a personal, revocable, non-exclusive, non-transferable right to access and use the Service, for non-commercial use only and private viewing only, in accordance with these Terms of Use. These Terms of Use, govern Your access of the Service and any data, message, text, image, audio, sound, voice, codes, computer programmes, software, database, micro film, video, information, content, etc. that You host, publish, share, transact, display and/or upload.
                </li>
                <li>
                  Please note that the availability of the Service in Your jurisdiction, and Your ability to access the Service is subject to the Company’s sole discretion. The Company may at its sole discretion restrict the Service from being accessed in certain geographical locations. You undertake that Your access of the Service shall be in compliance with all applicable laws (as amended from time-to-time). You understand that Your access of the Service and its contents may vary depending upon Your jurisdiction, device specifications, internet connection, etc. You acknowledge and agree that We will provide You only access to the Service and that You will be solely responsible for all equipment as may be necessary for You to access the internet, mobile and/or other connection, operator and service fees associated with Your access, etc.
                </li>
              </ol>

              <h4>OWNERSHIP OF INTELLECTUAL PROPERTY RIGHTS</h4>
              <p>The following terms shall have the meaning as ascribed to them below:</p>
              <ol>
                <li>"<b>Intellectual Property Rights</b>" shall mean all patents, trademarks, service marks, copyrights, database right, trade names, brand names, trade secrets, design rights and similar proprietary rights of the Company whether registered or unregistered and all renewals and extensions.
                </li>
                <li> All rights, title and interest in the Intellectual Property Rights in the Service including without limitation all its constituents, content, text, images, audios, audio-visuals, literary work, artistic work, musical work, computer programme, dramatic work, sound recording, cinematograph film, a video recording, performance and broadcast under the Copyright Act, 1957, specifications, instructions, abstracts, summaries, copy sketches, drawings, artwork, software, source code, object code, comments on the source code and object code, domain names, application names, designs, database, tools, icons, layout, programs, titles, names, manuals, graphics, animation, games, applications, user interface instructions, photographs, artist profiles, illustrations, jokes, memes, contests, and all other elements, data, information and materials ("<b>Materials</b>") are the property of the Company and/or its licensors and/or other respective owners and are protected, without limitation, pursuant to Intellectual Property Rights laws of India and the world. The Company retains full, complete and absolute title to the Service and all Intellectual Property Rights therein. </li>
                <li>The Service including any Materials thereon shall be deemed to be non-exclusively licensed to You by Us only for Your non-commercial personal use and only for such period as We may, in Our sole discretion, deem appropriate. You shall not use, reproduce, redistribute, sell, offer on commercial rental, decompile, reverse engineer, disassemble, adapt, communicate to the public, make a derivative work, interfere with the integrity of the Service (including without limitation the software, coding, constituents, elements, Materials, etc.) in any manner whatsoever.</li>
                <li>You expressly confirm not to, directly or indirectly, copy, reproduce, modify, edit, re-edit, amend, alter, vary, enhance, improve, upgrade, create derivative works, translate, adapt, abridge, delete, display, perform, publish, distribute, circulate, communicate to the public, disseminate, broadcast, transmit, sell, rent, lease, lend, assign, license, sub-license, disassemble, decompile, reverse engineer, market, promote, circulate, exploit, digitally alter or manipulate the Service (including any and all Materials therein) (in whole or in part) in any manner, medium or mode now know or hereinafter developed. </li>
              </ol>
              <h4>USER MATERIAL</h4>
              <ol>
                <li>The Service may allow Users to publish content, data, information, text, images, videos, audios, audio-visuals, User’s opinion, recommendation, advice, view, etc. ("<b>User Material</b>").  The User Material does not reflect the views of the Company. In no event shall the Company be held responsible for any User Material, neither does the Company endorse or recommend any User Material, nor shall the Company be liable for any loss or damages resulting from publishing of the User Material on the Service.</li>
                <li>
                  By submitting a User Material, You grant the Company a perpetual, worldwide, royalty-free, irrevocable, non-exclusive license to use, and authorize others to use the User Material in whole or in part, in any and all media, now known or hereinafter developed, including rights to use the User Material in isolation or in combination with any other material. You agree that in such circumstances, You are not entitled to any intimation or compensation from the Company.
                </li>
                <li>
                  The Company will have the right but no obligation to monitor, remove, suspend, destroy, use and change any User Material and/or content that is available on or via any chat area on the Service generally, if any, in any manner that the Company may its sole discretion determine, at any time. Although the Company may endeavor to periodically monitor the User Material posted on the Service, the Company will not be responsible for the same.
                </li>
                <li>In the event the Company hosts or puts up any reviews of any movies or programs, whether third party or own content or other such views, then the views shall demonstrate only the author’s views and not the views of the Company.
                </li>
                <li>
                  By posting User Material on the Service, You undertake, represent and warrant to the Company that: (a) the User Material is original; (b) does not infringe the rights of any third party including without limitation Intellectual Property Rights; and (c) is not -- defamatory, derogatory or abusive or malicious or hurtful to any person, particular entity, groups, caste, religion, race or community or seditious or pornographic or vulgar or in violation of any law.
                </li>
                <li>
                  You agree, covenant and undertake that You shall NOT host, display, upload, modify, publish, transmit, update or share any data, information, content or message that:
                  <ol>
                    <li>
                      belongs to another person and to which You do not have any right to;
                    </li>
                    <li>is grossly harmful, harassing, blasphemous defamatory, derogatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
                    </li>
                    <li>harm minors in any way;</li>
                    <li>infringes any patent, trademark, copyright or other proprietary rights or intellectual property rights;</li>
                    <li>violates any applicable national or international laws, regulations, rules and/or guidelines;</li>
                    <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                    <li>impersonates another person;</li>
                    <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                    <li>threatens the unity, national interest ,integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation/country;</li>
                    <li>is offensive or has menacing character; </li>
                    <li>causes annoyance, inconvenience, danger, obstruction, insult, injury, criminal intimidation, enmity, hatred or ill will;</li>
                    <li>causes annoyance or inconvenience or is intended to deceive or to mislead the addressee or recipient about the origin of such messages.</li>
                  </ol>
                </li>
                <li> You further undertake that You shall not use the Service to:
                  <ol>
                    <li>
                      violate the privacy right or personal right or confidential information of any person;
                    </li>
                    <li>
                      commit an act which could be construed as an act of cyber terrorism;
                    </li>
                    <li>
                      collect, store and/or identify private/personal information of any user or person;
                    </li>
                    <li>
                      facilitate personal attacks on other individuals, entity, groups, caste, religion, race or community;
                    </li>
                    <li>
                      stalk or otherwise harass another person or user;
                    </li>
                    <li>
                      upload, post or e-mail any content that You do not have a right to transmit under any law or under contract;
                    </li>
                    <li>
                      upload, post or e-mail any content that infringes privacy rights, intellectual property rights or other third-party rights of any person or party;
                    </li>
                    <li>
                      upload, post or e-mail any unsolicited or unauthorized advertising, promotional materials, junk- mail, spam, chain-letters or any other form of solicitation;
                    </li>
                    <li>
                      upload, post or e-mail any content that contains computer viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software, hardware, devices, platforms or telecommunications equipment and/or the Service;
                    </li>
                    <li>
                      interfere with, damage, disable, disrupt, impair, create an undue burden on, or gain unauthorized access to the Service, including the Company’s servers, networks or accounts;
                    </li>
                    <li>
                      disrupt the normal flow of dialogue, cause a screen to scroll faster than other users of the Service are able to type, or otherwise act in a manner that adversely affects other users’ ability to engage in real time exchanges;
                    </li>
                    <li>
                      cover, remove, disable, manipulate, block or obscure advertisements or other portions of the Service;
                    </li>
                    <li>
                      delete or revise any information provided by or pertaining to any other user of the Service;
                    </li>
                    <li>
                      promote and/or generate revenue for Yourself and/or any third-party business activity;
                    </li>
                    <li>
                      carry out any activity that is prohibited under the Act, including under Section 43, etc. and/or under any other applicable laws, rules or regulations;
                    </li>
                    <li>
                      post unauthorized commercial communications and including advertisements; and/or
                    </li>
                    <li>
                      manipulate or morph or alter or exploit any other User’s User Material.
                    </li>
                  </ol>
                </li>
                <li>You hereby confirm that the Company has the right to determine whether any content, data or information published by You on the Service is appropriate and complies with these Terms of Use, and accordingly remove any and/or all of Your User Material, and terminate Your access without prior notice. This shall be without prejudice to any other rights and remedies that the Company has under law and/or in equity and/or under this agreement.</li>
                <li>If You submit any User Material on the Service, You shall be deemed to have waived any rights, interest and ownership in the User Material and deemed to have put the contents of the User Material in the public domain, making it open to re-use, reproduction, distribution, communication to the public, adaptation, etc. You understand the risks associated with publishing User Material on the Service and agree that the Company shall not be responsible or liable for any digital alteration, manipulation, morphing, illegal exploitation, etc. of any User Material posted by You. </li>
                <li>You further agree that the Company shall not be responsible or liable to You for any threatening, defamatory, derogatory, obscene, offensive or illegal conduct by other users or any infringement of Your intellectual property rights, privacy rights, personal rights, etc. by other users of the Service. </li>
              </ol>
              <h4>CONTESTS AND PROMOTIONS</h4>
              <p>Any and all contests, promotions, surveys and campaigns hosted or conducted on the Service are subject to separate contest terms and conditions ("<b>Contest T&amp;Cs</b>") and You are requested to read the Contest T&amp;Cs as well as Terms of Use before participating in the same and upon participation it shall be deemed that the participant has read and understood the Contest T&amp;Cs. Terms of Use are deemed incorporated by reference into Contest T&amp;Cs provided in respect of a particular activity. </p>
              <h4>DISCLAIMER AND LIMITATION OF LIABILITY</h4>
              <ol><li>BY ACCESSING AND/OR USING THE SERVICE, YOU HAVE READ, UNDERSTOOD AND AGREE TO BE LEGALLY BOUND BY THE TERMS OF THIS DISCLAIMER. YOU AGREE THAT YOUR ACCESS TO THE SERVICE IS AT YOUR SOLE RISK AND AT YOUR FREE WILL.</li>
                <li>THE SERVICE AND ALL MATERIAL THEREIN CONTAINED ARE DISTRIBUTED AND TRANSMITTED BY THE COMPANY ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE COMPANY AND ITS AFFILIATES, ASSOCIATES AND GROUP COMPANIES, THEIR RESPECTIVE DIRECTORS, KEY MANAGERIAL PERSONNEL, EMPLOYEES, OFFICERS, SHAREHOLDERS, AGENTS, REPRESENTATIVES, SUB-CONTRACTORS, CONSULTANTS AND THIRD-PARTY PROVIDERS:
                  <ol>
                    <li>
                      DISCLAIM ANY AND ALL EXPRESS OR IMPLIED REPRESENTATIONS, WARRANTIES AND/OR CONDITIONS OF ANY KIND, INCLUDING BUT NOT LIMITED TO WARRANTIES OF COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY, FITNESS, MERCHANTABILITY,  AVAILABILITY, QUALITY, FITNESS FOR ANY PURPOSE, NON-INFRINGEMENT, COMPATIBILITY AND/OR SECURITY;
                    </li>
                    <li>
                      ARE NOT RESPONSIBLE OR LIABLE FOR ANY INFECTION OR CONTAMINATION OF YOUR SYSTEM OR DEVICE ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE OR ANY CONNECTED SERVICE AND DO NOT WARRANT THAT THE SERVICE, THE SERVER(S) THAT MAKE THE SERVICE AVAILABLE OR ANY CONNECTED SERVICES ARE FREE FROM VIRUSES, TROJAN HORSES, WORMS, SOFTWARE BOMBS OR SIMILAR ITEMS OR PROCESSES OR OTHER HARMFUL COMPONENTS;
                    </li>
                    <li>ARE NOT RESPONSIBLE OR LIABLE FOR INTERRUPTIONS, DELAYS, INACCURACIES, ERRORS, OR OMISSIONS ARISING OUT OF YOUR USE OF THE SERVICE OR ANY CONNECTED SERVICE OR WITH RESPECT TO THE MATERIAL AND USER MATERIAL THEREON; AND </li>
                    <li>DO NOT WARRANT THAT THE SERVICE, OR ANY CONNECTED SERVICE, LINKED MICROSITES, ANY MATERIALS, THIRD-PARTY CONTENT, SERVICES OFFERED WILL BE UNINTERRUPTED OR ERROR FREE OR ACCURATE OR SUIT YOUR PURPOSE.</li>
                  </ol>
                  <ol>
                    <li>
                      EVERY EFFORT IS MADE TO KEEP THE SERVICE RUNNING SMOOTHLY. HOWEVER, THE COMPANY TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE FOR, THE SERVICE BEING UNAVAILABLE DUE TO ANY REASONS.
                    </li>
                    <li>
                      THE ENTIRE RISK AS TO THE QUALITY, ACCURACY, ADEQUACY, COMPLETENESS, FITNESS, CORRECTNESS AND VALIDITY OF ANY MATERIAL AND USE OF AND ACCESS TO THE SERVICE OR ANY CONNECTED SERVICE RESTS SOLELY WITH YOU.
                    </li>
                    <li>THE SERVICE MAY CONTAIN LINKS TO OTHER THIRD-PARTY WEBSITES/SERVICES WHICH ARE NOT UNDER THE CONTROL OF THE COMPANY. ANY WEBSITE YOU VISIT BY A LINK FROM THE SERVICE IS SOLELY THE RESPONSIBILITY OF THE THIRD PARTY PROVIDING THE WEBSITE. THE CONTENT OF, INCLUDING MATERIALS AND INFORMATION CONTAINED ON, ANY THIRD PARTY WEBSITE TO WHICH YOU LINK FROM THE SERVICE IS SOLELY THE RESPONSIBILITY OF THE PROVIDER OF THAT THIRD PARTY WEBSITE. ANY TRANSACTIONS THAT YOU ENTER INTO WITH A THIRD PARTY LISTED IN THIS SERVICE OR LINKED FROM THIS SERVICE ARE SOLELY BETWEEN YOU AND THAT THIRD PARTY. WE ARE NOT RESPONSIBLE FOR ANY SUCH THIRD-PARTY CONTENT THAT MAY BE ACCESSED VIA THE SERVICE, NOR THE ORGANIZATIONS PUBLISHING THOSE THIRD PARTY WEBSITES, AND HEREBY DISCLAIM ANY RESPONSIBILITY AND LIABILITY FOR SUCH CONTENT. THE INCLUSION OF ANY LINKS DOES NOT CONSTITUTE OR IMPLY AN ENDORSEMENT OR RECOMMENDATION BY US OF THE THIRD-PARTY, OF THE QUALITY OF ANY PRODUCT OR SERVICE, ADVICE, INFORMATION OR OTHER MATERIALS DISPLAYED, PURCHASED, OR OBTAINED BY YOU AS A RESULT OF AN ADVERTISEMENT OR ANY OTHER INFORMATION OR OFFER IN OR IN CONNECTION WITH THE THIRD PARTY WEBSITE.</li>
                    <li>TO THE FULLEST EXTENT PERMISSIBLE BY LAW, THE COMPANY, ITS AFFILIATES, ASSOCIATES AND GROUP COMPANIES, AND THEIR RESPECTIVE DIRECTORS, KEY MANAGERIAL PERSONNEL, EMPLOYEES, OFFICERS, SHAREHOLDERS, AGENTS, REPRESENTATIVES, SUB-CONTRACTORS, CONSULTANTS AND THIRD-PARTY PROVIDERS SHALL NOT BE LIABLE FOR ANY LOSS AND/OR DAMAGE AND/OR CLAIMS OF ANY KIND (WHETHER IN CONTRACT, TORT OR BREACH OF STATUTORY DUTY OR OTHERWISE) ARISING OUT OF OR IN CONNECTION WITH THE SERVICE AND/OR MATERIALS AND/OR USER MATERIAL AND/OR ANY CONNECTED THIRD PARTY WEBSITE INCLUDING WITHOUT LIMITATION:
                      <ol>
                        <li>INDIRECT OR CONSEQUENTIAL LOSS; </li>
                        <li>LOSS OF PROFITS OR REVENUE OR SAVINGS OR OTHER ECONOMIC LOSS; </li>
                        <li>INCIDENTAL, DIRECT, OR SPECIAL LOSS OR SIMILAR DAMAGES; </li>
                        <li>LOSS OF OR DAMAGE TO DATA; </li>
                        <li>LOSS OF BUSINESS, REPUTATION OR GOODWILL; AND/OR </li>
                        <li>WASTED OR LOST MANAGEMENT TIME;</li>
                        <p>EVEN IF ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE OR IF SUCH LOSS OR DAMAGE WAS FORESEEABLE.</p>
                      </ol>
                    </li>
                    <li>
                      NOTWITHSTANDING THE FOREGOING, IN NO EVENT SHALL THE COMPANY OR ITS AFFILIATES, ASSOCIATES AND GROUP COMPANIES’ LIABILITY TO YOU FOR ANY AND ALL LOSSES, DAMAGES OR CLAIMS (WHETHER IN CONTRACT, TORT, BREACH OF STATUTORY DUTY OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE SERVICE.
                    </li>
                    <li>IF YOU ARE DISSATISFIED WITH THE SERVICE OR WITH THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING OR USING THE SERVICE.</li>
                  </ol>
                </li>
              </ol>
              <h4>INDEMNITY </h4>
              <p>YOU AGREE TO FULLY INDEMNIFY, DEFEND AND HOLD HARMLESS THE COMPANY, ITS AFFILIATES, ASSOCIATES AND GROUP COMPANIES, AND THEIR RESPECTIVE DIRECTORS, KEY MANAGERIAL PERSONNEL, EMPLOYEES, OFFICERS, SHAREHOLDERS, AGENTS, REPRESENTATIVES, SUB-CONTRACTORS, CONSULTANTS AND THIRD-PARTY PROVIDERS FROM AND AGAINST ALL LOSSES, CLAIMS AND DAMAGES INCLUDING LEGAL FEES, RESULTING FROM: (I) YOUR VIOLATION OF ANY TERM OF THESE TERMS OF USE; (III) YOUR VIOLATION OF ANY THIRD PARTY RIGHT, INCLUDING WITHOUT LIMITATION ANY PUBLICITY, PRIVACY, OR INTELLECTUAL PROPERTY RIGHT; (IV) YOUR BREACH OF ANY APPLICABLE LAWS; (IV) ANY UNAUTHORIZED, IMPROPER, ILLEGAL OR WRONGFUL USE OF YOUR ACCOUNT BY ANY PERSON, INCLUDING A THIRD PARTY, WHETHER OR NOT AUTHORIZED OR PERMITTED BY YOU; AND (V) YOUR BREACH OF ANY REPRESENTATION, WARRANTY, COVENANT OR UNDERTAKING UNDER THESE TERMS OF USE OR UNDER APPLICABLE LAW. THIS INDEMNIFICATION OBLIGATION WILL SURVIVE THE EXPIRY OR TERMINATION OF THESE TERMS OF USE AND YOUR USE OF THE SERVICE.  </p>
              <h4>THIRD PARTY WEBSITES</h4>
              <ol>
                <li>
                  This Service may contain links to other websites owned and operated by third parties who are not related to the Company ("<b>Third-Party Websites</b>"). Third-Party Websites are not under the control of the Company and the Company shall not be responsible for the content of any Third-Party Websites or any hyperlink contained in a Third-Party Websites and makes no representation or warranty with respect to the content of any such Third-Party Websites.
                </li>
                <li>
                  Your access and usage of any Third-Party Websites is entirely at Your own risk. The Company shall not be a party to any transaction between You and a Third-Party Website. Your use of a Third-Party Website is subject to the terms and conditions of that Third-Party Websites in addition to these Terms of Use. If there is any inconsistency these Terms of Use prevail.
                </li>
                <li>
                  The Service may contain third party advertisements, promotions, etc. (that may or may not contain embedded hyperlinks or referral buttons to Third-Party Websites). The display of such advertising does not in any way imply an endorsement or recommendation by the Company of the relevant advertiser, its products or services or any such Third-Party Website. You must refer directly to the relevant advertiser for all information regarding the advertiser and its products and/or services. The Company accepts no responsibility for any interaction between You and the relevant third party and is released from any liability arising out of or in any way connected with such interaction and/or any defects, deficiencies, claims, etc. arising out of an advertiser’s products and/or services.
                </li>
              </ol>
              <h4>NOTICE &amp; TAKE DOWN PROCESS</h4>
              <ol>
                <li>
                  The Company does not endorse or promote any data, information, content or material published on the Service including User Material, and expressly disclaims any and all liability in connection with the same.
                </li>
                <li>
                  If You believe that the Service contains any data, information, content or material that could be in violation of Clause 6 and/or in violation of Clause 7 under Use Material and/or in violation of any applicable provision of the Act or rules thereunder, You may notify the Company of the same by sending an email notification at <a href='mailto:support@voot.com'>support@voot.com</a>. By doing so, please remember that You are initiating a legal process. Do not make false claims. Misuse of this process may result in the suspension of Your account and/or other legal consequences. Please note that this provision shall be governed by applicable laws in India including relevant provisions of the Act. You may seek independent legal advice with respect to this legal procedure at Your sole cost, expense and consequences.
                </li>
                <li>
                  The Company shall take-down any data, information, content or material only upon receiving actual knowledge from a court order or on being notified by the appropriate government or its agency that unlawful acts relatable to Article 19(2) would be committed if the said data, information, content or material is not deleted from the Service.
                </li>
                <li>
                  The Company further reserves the right (without the obligation of doing so) to take-down any data, information, content or material, without notice to User and without any liability either to the Company or its directors, key managerial personnel, officers, employees, that the Company in its sole discretion determines to be in violation of Clause 6 and/or in violation of Clause  7 under Use Material and/or in violation of any applicable provision of the Act or rules thereunder.
                </li>
              </ol>
              <h4>SUPPORT</h4>
              <p>If You have any questions or queries with respect to the Service, then such correspondence should be directed at <a href='mailto:support@voot.com'>support@voot.com</a>.</p>
              <h4>TERMINATION</h4>
              <p>The Company reserves the right to terminate Your access to all or part of the Service, at its sole discretion, without notice and without liability either to the Company or its directors, key managerial personnel, officers, employees, either for convenience or for any reason, including in the event of suspected or actual breach by You of any of these Terms of Use, the Privacy Policy, violation of any law including the Act and/or rules thereunder or any other regulation, or for any other reason that the Company deems fit. </p>
              <h4>MISCELLANEOUS</h4>
              <ol>
                <li>
                  The fastest and easiest way to notify the Company of any grievance is by sending an email notification to Our grievance officer at <a href='mailto:support@voot.com'>support@voot.com</a>.
                </li>
                <li>
                  These Terms of Use contain the entire understanding between You and the Company and supersedes all prior understanding between the User and the Company in respect of the User's access and/or use of the Service.
                </li>
                <li>
                  If any provision of these Terms of Use is found to be illegal, invalid or unenforceable, then to the extent to which such provision is illegal, invalid or otherwise unenforceable, it shall be severed and deleted and the remaining provisions shall survive and remain in full force and effect and continue to be binding and enforceable.
                </li>
                <li>
                  You confirm that Your representations, warranties, undertakings and covenants, and the clauses relating to indemnities, limitation of liability, grant of license, governing law, confidentiality shall survive the efflux of time and the termination of these Terms of Use.
                </li>
                <li>
                  Any express waiver or failure to exercise promptly any right under these Terms of Use will not create a continuing waiver or any expectation of non-enforcement.
                </li>
                <li>
                  You agree that the Company shall be under no liability whatsoever to You in the event of non-availability of the Service or any portion thereof occasioned by Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, network failures, server failures, failure of any public utility, terrorist attack, network maintenance, Service maintenance, server maintenance, or any other cause whatsoever beyond the control of the Company.
                </li>
                <li>
                  Unless otherwise specified, the Service is presented solely for the purpose of entertainment and promoting programs. The Company makes no representation that the Service is appropriate or available for use in locations other than India. Those who choose to access the Service from locations other than in India, do so on their own initiative and risk, and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.
                </li>
                <li>
                  The Privacy Policy (as provided on the Service), and any other documents, instructions, etc. included on the Service shall be read into this and shall be a part of these Terms of Use. The Privacy Policy shall form an integral part of the Terms of Use and both these documents constitute the user agreement and a legally binding contract between the Company and the User.
                </li>
                <li>
                  These Terms of Use shall be governed by and construed in accordance with the laws of the India and be subject to the exclusive jurisdiction of the Courts at Mumbai, without giving effect to any principles of conflicts of law.
                </li>
              </ol>
            </div>
          </div>
        </section>
      </div>
    );
  }
}
