import appConfigs from '../appConfig';
let appConfig = appConfigs.default;

export const apiUrl = {
  BASE: appConfig.BASE,
  AUTH: appConfig.AUTH,

  apiLR: 'https://api.loginradius.com/api/v2/',
  access_tokenLR: 'access_token',
  userProfileLR: 'userprofile',
  authentication: 'authentication.json',
  getProfile: 'getProfile.json',
  createProfile: 'create.json',
  passwordChange: 'passwordChange.json',
  accountPasswordSet: 'accountPasswordSet.json',
  checkEmail: 'checkEmail.json',
  kalturaLogin: 'kUserLogin.json',
  kalturaRegistration: 'kUserReg.json',
  editProfile: 'edit.json',
  country: 'country.json',
  home: 'home.json',
  ottSearchAssets: 'ott/searchAssets.json',
  ottSearchMediaByAndOrList: 'ott/searchMediaByAndOrList.json',
  ottGetAutoCompleteSearch: 'ott/getAutoCompleteSearch.json',
  ottGetMediaInfo: 'ott/getMediaInfo.json',
  ottGetRelatedMediasByTypes: 'ott/getRelatedMediasByTypes.json',
  vootSeriesShorts: 'media/vootSeriesShorts.json',
  showsListWithAssetsCounts: 'media/showsListWithAssetsCounts.json',
  voShowList: 'media/voShowsList.json',
  popularShowsList: 'media/popularShowsList.json',
  getChannelMedias: 'media/getChannelMedias.json',
  getSeasons: 'media/getSeasons.json',
  showList: 'showList.json',
  playList: 'playList.json',
  voPlayList: 'voPlayList.json',
  tvSeries: 'media/tvSeries.json',
  vootOriginalTvSeries: 'media/vootOriginalTvSeries.json',
  movies: 'media/movies.json',
  getTopShoutCount: 'media/getTopShoutCount.json',
  getTvSeriesTopShout: 'media/getTvSeriesTopShout.json',
  shoutList: 'shout/list.json',
  shoutByUser: 'shout/shoutByUser.json',
  makeShoutOnMedia: 'shout/makeShoutOnMedia.json',
  isFollowed: 'follow/isFollowed.json',
  followList: 'follow/list.json',
  followAdd: 'follow/add.json',
  followRemove: 'follow/remove.json',
  adultPopularSearch: 'misc/adultPopularSearch.json',
  adultSearch: 'adultSearch.json',
  channelList: 'channel/list.json',
  channelHome: 'channel/home.json',
  kidsHome: 'kids/home.json',
  kidsCluster: 'kids/cluster.json',
  kidsSeries: 'kids/series.json',
  kidsSeriesImages: 'kids/seriesImages.json',
  kidsSearch: 'kidsSearch.json',
  kidsPopularSearch: 'misc/kidsPopularSearch.json',
};

