export const SEARCH_ASSET = {
  SUCCESS: 'SEARCH_ASSET_SUCCESS',
  FAILURE: 'SEARCH_ASSET_FAILURE',
};

export const CLIP_SEARCH_ASSET = {
  SUCCESS: 'CLIP_SEARCH_ASSET_SUCCESS',
  FAILURE: 'CLIP_SEARCH_ASSET_FAILURE',
};


export const CLIP_GET_MEDIA_INFO = {
  SUCCESS: 'CLIP_GET_MEDIA_INFO_SUCCESS',
  CLEAR: 'CLIP_GET_MEDIA_INFO_CLEAR',
  FAILURE: 'CLIP_GET_MEDIA_INFO_FAILURE',
};

export const CLIP_GET_RELATED_MEDIA = {
  SUCCESS: 'CLIP_GET_RELATED_MEDIA_SUCCESS',
  FAILURE: 'CLIP_GET_RELATED_MEDIA_FAILURE',
};

